### ISSUE TITLE
There is a 1px difference between Metropolis (r8) and Clarity City

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity-city#4]
There is a subtle 1px different in the glyph placement. This was found when swapping Clarity City into [Clarity](https://github.com/vmware/clarity) as the primary font.

When comparing the current version of Metropolis (r8) used in Clarity with Clarity City visual regression testing shows that there is a subtle 1px difference in the placement of each glyph. As far as I can tell each Glyph has the same height.

Clarity City needs to be investigated to determine if the Metropolis (r8) glyph baseline is correct or the Metropolis (r9) / Clarity City baseline is correct. 

Here is the same app with the same window size comparing Metropolis (r8) with Clarity City:
![Screen Shot 2020-01-28 at 5 36 43 PM](https://user-images.githubusercontent.com/433692/73405045-d5133980-42a7-11ea-919e-27b89e0b31a4.png)

**Comment by gnomeontherun** [comment]
We spent a while trying to resolve this and never were able to identify the source. However, with Clarity Core taking in Clarity City we can close this as no longer a blocker.
