### ISSUE TITLE
Add Clarity City to Google Fonts

### ISSUE THREAD

**Issue by onlydole** [vmware/clarity-city#9]
### Is your feature request related to a problem? Please describe.

This is not a feature request related to a problem and it pertains more to usage and utilization.

### Describe the solution you'd like

I would like to utilize the Clarity City typeface in my Google docs, slides, and sheets. Adding this typeface to Google Fonts will help achieve that outcome and make this typeface more discoverable. 

### Additional context

The repository to submit OFL licensed typefaces can be found here: https://github.com/google/fonts/issues/new?assignees=&labels=I+New+Font%2C+II+Submission&template=1_add-font.md&title=Add+%5BFont+Name%5D

**Comment by tenthirtyam** [comment]
Isn't this a duplication of #7?

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by onlydole** [comment]
It is!

**Comment by tenthirtyam** [comment]
Thanks for confirming, @onlydole. 👍 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
